questions = [
{"question": "Linuxで現在のディレクトリを表示するコマンドは？", "options": ["ls", "pwd", "cd", "mkdir"], "answer": "pwd"},
{"question": "ファイルやディレクトリの一覧を表示するコマンドは？", "options": ["ls", "touch", "rm", "echo"], "answer": "ls"},
{"question": "新しいディレクトリを作成するコマンドは？", "options": ["rm", "mkdir", "rmdir", "cd"], "answer": "mkdir"},
{"question": "ファイルの中身を表示するコマンドは？", "options": ["cat", "ls", "echo", "touch"], "answer": "cat"},
{"question": "現在のユーザー名を表示するコマンドは？", "options": ["whoami", "id", "useradd", "passwd"], "answer": "whoami"},
{"question": "ファイルを削除するコマンドは？", "options": ["rm", "touch", "mkdir", "cp"], "answer": "rm"},
{"question": "ディレクトリを削除するコマンドは？", "options": ["rmdir", "rm", "cd", "mkdir"], "answer": "rmdir"},
{"question": "ファイルをコピーするコマンドは？", "options": ["cp", "mv", "rm", "touch"], "answer": "cp"},
{"question": "ファイル名を変更/移動するコマンドは？", "options": ["mv", "cp", "rm", "touch"], "answer": "mv"},
{"question": "新しい空ファイルを作成するコマンドは？", "options": ["touch", "mkdir", "echo", "cat"], "answer": "touch"},
{"question": "現在の作業ディレクトリを移動するコマンドは？", "options": ["cd", "pwd", "ls", "mkdir"], "answer": "cd"},
{"question": "ユーザーを追加するコマンドは？", "options": ["useradd", "usermod", "passwd", "whoami"], "answer": "useradd"},
{"question": "ユーザーのパスワードを変更するコマンドは？", "options": ["passwd", "useradd", "id", "chmod"], "answer": "passwd"},
{"question": "現在ログインしているユーザーを確認するコマンドは？", "options": ["who", "whoami", "users", "id"], "answer": "whoami"},
{"question": "ファイルのパーミッションを変更するコマンドは？", "options": ["chmod", "chown", "chgrp", "ls"], "answer": "chmod"},
{"question": "ファイルやディレクトリの所有者を変更するコマンドは？", "options": ["chown", "chmod", "chgrp", "ls"], "answer": "chown"},
{"question": "ファイルのグループを変更するコマンドは？", "options": ["chgrp", "chmod", "chown", "groups"], "answer": "chgrp"},
{"question": "ファイルの最終更新日時を確認するコマンドは？", "options": ["ls -l", "stat", "date", "touch"], "answer": "stat"},
{"question": "シンボリックリンクを作成するコマンドは？", "options": ["ln -s", "ln", "cp", "mv"], "answer": "ln -s"},
{"question": "ファイルを圧縮するコマンドは？", "options": ["gzip", "tar", "zip", "unzip"], "answer": "gzip"},
{"question": "tarファイルを作成するコマンドは？", "options": ["tar -cvf", "tar -xvf", "gzip", "zip"], "answer": "tar -cvf"},
{"question": "tarファイルを解凍するコマンドは？", "options": ["tar -xvf", "tar -cvf", "gzip -d", "unzip"], "answer": "tar -xvf"},
{"question": "ファイルの先頭10行を表示するコマンドは？", "options": ["head", "tail", "less", "more"], "answer": "head"},
{"question": "ファイルの最後10行を表示するコマンドは？", "options": ["tail", "head", "less", "more"], "answer": "tail"},
{"question": "ファイルをページごとに表示するコマンドは？", "options": ["less", "more", "cat", "tail"], "answer": "less"},
{"question": "コマンドのマニュアルを表示するコマンドは？", "options": ["man", "help", "--help", "info"], "answer": "man"},
{"question": "システム日時を表示するコマンドは？", "options": ["date", "time", "clock", "timedatectl"], "answer": "date"},
{"question": "システムの稼働時間を確認するコマンドは？", "options": ["uptime", "who", "top", "ps"], "answer": "uptime"},
{"question": "現在起動しているプロセスを確認するコマンドは？", "options": ["ps", "top", "htop", "jobs"], "answer": "ps"},
{"question": "リアルタイムでプロセス情報を確認するコマンドは？", "options": ["top", "ps", "htop", "jobs"], "answer": "top"},
{"question": "特定のプロセスを終了するコマンドは？", "options": ["kill", "pkill", "xkill", "stop"], "answer": "kill"},
{"question": "特定の名前のプロセスを終了するコマンドは？", "options": ["pkill", "kill", "killall", "stop"], "answer": "pkill"},
{"question": "ジョブ管理でバックグラウンドに送るコマンドは？", "options": ["bg", "fg", "jobs", "kill"], "answer": "bg"},
{"question": "バックグラウンドジョブをフォアグラウンドに戻すコマンドは？", "options": ["fg", "bg", "jobs", "kill"], "answer": "fg"},
{"question": "全てのジョブを表示するコマンドは？", "options": ["jobs", "ps", "top", "bg"], "answer": "jobs"},
{"question": "ファイルを検索するコマンドは？", "options": ["find", "grep", "locate", "which"], "answer": "find"},
{"question": "コマンド出力から特定の文字列を検索するコマンドは？", "options": ["grep", "find", "awk", "sed"], "answer": "grep"},
{"question": "コマンドのパスを表示するコマンドは？", "options": ["which", "whereis", "type", "locate"], "answer": "which"},
{"question": "コマンドの簡易情報を表示するコマンドは？", "options": ["whereis", "which", "man", "info"], "answer": "whereis"},
{"question": "ファイルの文字列を置換するコマンドは？", "options": ["sed", "awk", "grep", "cut"], "answer": "sed"},
{"question": "ファイルを行単位で処理するコマンドは？", "options": ["awk", "sed", "grep", "cut"], "answer": "awk"},
{"question": "テキストの切り取りに使うコマンドは？", "options": ["cut", "awk", "sed", "grep"], "answer": "cut"},
{"question": "ディスク使用量を表示するコマンドは？", "options": ["df", "du", "ls", "fdisk"], "answer": "df"},
{"question": "ディレクトリごとの使用容量を表示するコマンドは？", "options": ["du", "df", "ls", "tree"], "answer": "du"},
{"question": "マウントされているファイルシステムを確認するコマンドは？", "options": ["mount", "df", "lsblk", "blkid"], "answer": "mount"},
{"question": "ブロックデバイスの一覧を表示するコマンドは？", "options": ["lsblk", "blkid", "df", "mount"], "answer": "lsblk"},
{"question": "ファイルシステムのUUIDを確認するコマンドは？", "options": ["blkid", "lsblk", "mount", "df"], "answer": "blkid"},
{"question": "パッケージをインストールするコマンド（Debian系）は？", "options": ["apt install", "yum install", "dnf install", "pacman -S"], "answer": "apt install"},
{"question": "パッケージを削除するコマンド（Debian系）は？", "options": ["apt remove", "yum remove", "dnf remove", "pacman -R"], "answer": "apt remove"},
{"question": "パッケージリストを更新するコマンド（Debian系）は？", "options": ["apt update", "apt upgrade", "yum update", "dnf update"], "answer": "apt update"},
{"question": "システム全体をアップデートするコマンド（Debian系）は？", "options": ["apt upgrade", "apt update", "yum update", "dnf upgrade"], "answer": "apt upgrade"},
{"question": "現在のIPアドレスを確認するコマンドは？", "options": ["ip addr", "ifconfig", "netstat", "ping"], "answer": "ip addr"},
{"question": "ネットワーク疎通を確認するコマンドは？", "options": ["ping", "traceroute", "curl", "wget"], "answer": "ping"},
{"question": "ルーティングテーブルを表示するコマンドは？", "options": ["route", "ip route", "netstat -r", "traceroute"], "answer": "route"},
{"question": "サービスの状態を確認するコマンドは？", "options": ["systemctl status", "service status", "ps", "top"], "answer": "systemctl status"},
{"question": "サービスを起動するコマンドは？", "options": ["systemctl start", "service start", "init start", "run start"], "answer": "systemctl start"},
{"question": "サービスを停止するコマンドは？", "options": ["systemctl stop", "service stop", "init stop", "kill"], "answer": "systemctl stop"},
{"question": "サービスを再起動するコマンドは？", "options": ["systemctl restart", "service restart", "init restart", "kill -HUP"], "answer": "systemctl restart"},
{"question": "カーネルログを確認するコマンドは？", "options": ["dmesg", "journalctl", "tail /var/log/syslog", "logread"], "answer": "dmesg"},
{"question": "システムログを確認するコマンドは？", "options": ["journalctl", "dmesg", "tail /var/log/syslog", "logread"], "answer": "journalctl"},
{"question": "現在のディスク容量を確認するコマンドは？", "options": ["df -h", "du -h", "ls -lh", "fdisk -l"], "answer": "df -h"},
{"question": "ファイルの中身をリアルタイムで監視するコマンドは？", "options": ["tail -f", "less", "head -f", "cat -f"], "answer": "tail -f"},
{"question": "現在のカレントディレクトリの絶対パスを表示するコマンドは？", "options": ["pwd", "cd", "ls -d", "echo $PWD"], "answer": "pwd"},
{"question": "シェルで変数の値を表示するコマンドは？", "options": ["echo", "print", "show", "cat"], "answer": "echo"},
{"question": "シェルの履歴を表示するコマンドは？", "options": ["history", "log", "cat ~/.bash_history", "echo $HIST"], "answer": "history"},
{"question": "ファイルの種類を確認するコマンドは？", "options": ["file", "ls -l", "stat", "type"], "answer": "file"},
{"question": "実行可能ファイルか確認するコマンドは？", "options": ["file", "ls -l", "which", "type"], "answer": "file"},
{"question": "シェルでコマンドのエイリアスを作成するコマンドは？", "options": ["alias", "export", "set", "env"], "answer": "alias"},
{"question": "環境変数を設定するコマンドは？", "options": ["export", "alias", "set", "env"], "answer": "export"},
{"question": "ユーザーが属するグループを確認するコマンドは？", "options": ["groups", "id", "whoami", "getent"], "answer": "groups"},
{"question": "システムの稼働中プロセスをツリー表示するコマンドは？", "options": ["pstree", "ps", "top", "jobs"], "answer": "pstree"},
{"question": "CPU情報を確認するコマンドは？", "options": ["lscpu", "cat /proc/cpuinfo", "top", "htop"], "answer": "lscpu"},
{"question": "メモリ情報を確認するコマンドは？", "options": ["free", "top", "htop", "vmstat"], "answer": "free"},
{"question": "シェルを終了するコマンドは？", "options": ["exit", "logout", "Ctrl+D", "quit"], "answer": "exit"},
{"question": "システム再起動するコマンドは？", "options": ["reboot", "shutdown -r now", "init 6", "systemctl reboot"], "answer": "reboot"},
{"question": "システムをシャットダウンするコマンドは？", "options": ["shutdown", "poweroff", "halt", "systemctl poweroff"], "answer": "shutdown"},
{"question": "マウントされているディスクの空き容量を確認するコマンドは？", "options": ["df -h", "du -sh", "lsblk", "fdisk -l"], "answer": "df -h"},
{"question": "特定のポートで待機しているプロセスを確認するコマンドは？", "options": ["netstat -tulnp", "lsof -i", "ss -tulnp", "fuser"], "answer": "netstat -tulnp"},
{"question": "ポートの使用状況を確認するコマンドは？", "options": ["ss -tulnp", "netstat -an", "lsof -i", "fuser"], "answer": "ss -tulnp"},
{"question": "IPアドレスの疎通を確認するコマンドは？", "options": ["ping", "traceroute", "curl", "wget"], "answer": "ping"},
{"question": "経路を確認するコマンドは？", "options": ["traceroute", "ping", "netstat", "route"], "answer": "traceroute"},
{"question": "ファイアウォールの状態を確認するコマンドは？", "options": ["ufw status", "iptables -L", "firewall-cmd --state", "systemctl status firewalld"], "answer": "ufw status"},
{"question": "iptablesのルールを確認するコマンドは？", "options": ["iptables -L", "iptables -F", "iptables -A", "iptables -D"], "answer": "iptables -L"},
{"question": "Linuxでユーザーを削除するコマンドは？", "options": ["userdel", "deluser", "rmuser", "deleteuser"], "answer": "userdel"},
{"question": "ファイルに実行権限を付与するコマンドは？", "options": ["chmod +x", "chmod 755", "chown", "chgrp"], "answer": "chmod +x"},
{"question": "ファイルをバックグラウンドでコピーするコマンドは？", "options": ["cp &", "cp", "rsync", "scp"], "answer": "cp &"},
{"question": "リモートサーバーにファイルをコピーするコマンドは？", "options": ["scp", "rsync", "ftp", "sftp"], "answer": "scp"},
{"question": "rsyncコマンドの基本用途は？", "options": ["同期", "コピー", "移動", "削除"], "answer": "同期"},
{"question": "リモートサーバーにSSH接続するコマンドは？", "options": ["ssh", "telnet", "rlogin", "ftp"], "answer": "ssh"},
{"question": "現在のシェルを確認するコマンドは？", "options": ["echo $SHELL", "echo $0", "ps -p $$", "env"], "answer": "echo $SHELL"},
{"question": "環境変数を確認するコマンドは？", "options": ["env", "set", "printenv", "export"], "answer": "env"},
{"question": "ファイルのバイト数を確認するコマンドは？", "options": ["stat", "ls -l", "du -b", "wc -c"], "answer": "stat"},
{"question": "テキストファイルの行数を数えるコマンドは？", "options": ["wc -l", "wc -w", "wc -c", "grep -c"], "answer": "wc -l"},
{"question": "gzipで圧縮したファイルを解凍するコマンドは？", "options": ["gzip -d", "gunzip", "tar -xzvf", "unzip"], "answer": "gunzip"},
{"question": "zipファイルを解凍するコマンドは？", "options": ["unzip", "tar -xvf", "gunzip", "zip -d"], "answer": "unzip"},
{"question": "現在のカレントディレクトリ内の全ファイルを再帰的に検索するコマンドは？", "options": ["find . -name 'ファイル名'", "grep 'ファイル名'", "locate 'ファイル名'", "whereis 'ファイル名'"], "answer": "find . -name 'ファイル名'"},
{"question": "特定の文字列を含む行を検索するコマンドは？", "options": ["grep '文字列' ファイル名", "find '文字列' ファイル名", "awk '/文字列/' ファイル名", "sed -n '/文字列/p' ファイル名"], "answer": "grep '文字列' ファイル名"},
{"question": "圧縮tar.gzファイルを展開するコマンドは？", "options": ["tar -xzvf ファイル名", "tar -cvzf ファイル名", "gzip -d ファイル名", "unzip ファイル名"], "answer": "tar -xzvf ファイル名"},
{"question": "現在のシステムユーザー一覧を表示するコマンドは？", "options": ["cat /etc/passwd", "getent passwd", "who", "users"], "answer": "cat /etc/passwd"},
{"question": "現在ログインしている全ユーザーを表示するコマンドは？", "options": ["who", "w", "users", "id"], "answer": "who"},
{"question": "現在のシェルのPIDを確認するコマンドは？", "options": ["echo $$", "echo $PPID", "ps -p $$", "pidof bash"], "answer": "echo $$"},
{"question": "標準出力をファイルにリダイレクトする記号は？", "options": [">", ">>", "<", "|"], "answer": ">"},
{"question": "標準出力を追記でファイルにリダイレクトする記号は？", "options": [">>", ">", "<", "|"], "answer": ">>"},
{"question": "標準エラーを標準出力にリダイレクトする記号は？", "options": ["2>&1", "1>2", "2>1", ">&"], "answer": "2>&1"},
{"question": "コマンドをパイプでつなぐ記号は？", "options": ["|", "&", ";", "&&"], "answer": "|"},
{"question": "ジョブを停止するキーボードショートカットは？", "options": ["Ctrl+Z", "Ctrl+C", "Ctrl+D", "Ctrl+S"], "answer": "Ctrl+Z"},
{"question": "ジョブを強制終了するキーボードショートカットは？", "options": ["Ctrl+C", "Ctrl+Z", "Ctrl+D", "Ctrl+S"], "answer": "Ctrl+C"},
{"question": "Linuxのシェルは何を指す？", "options": ["コマンドを解釈するプログラム", "OSカーネル", "ファイルシステム", "テキストエディタ"], "answer": "コマンドを解釈するプログラム"},
{"question": "ユーザーを一時的にスーパーユーザーに切り替えるコマンドは？", "options": ["sudo", "su", "login", "switch"], "answer": "sudo"},
{"question": "ルートユーザーに切り替えるコマンドは？", "options": ["su", "sudo", "login", "switch"], "answer": "su"},
{"question": "Linuxで一般ユーザーに権限を付与するコマンドは？", "options": ["chmod", "chown", "usermod", "groupadd"], "answer": "chmod"},
{"question": "ファイルのアクセス権を確認するコマンドは？", "options": ["ls -l", "stat", "file", "getfacl"], "answer": "ls -l"},
{"question": "ユーザーのIDとグループIDを確認するコマンドは？", "options": ["id", "whoami", "groups", "getent"], "answer": "id"},
{"question": "端末にログインしたユーザーを確認するコマンドは？", "options": ["w", "who", "users", "id"], "answer": "w"},
{"question": "コマンドの履歴を検索するコマンドは？", "options": ["history | grep 'コマンド'", "grep history", "cat ~/.bash_history", "history -i"], "answer": "history | grep 'コマンド'"},
{"question": "Linuxでファイルを比較するコマンドは？", "options": ["diff", "cmp", "comm", "compare"], "answer": "diff"},
{"question": "システムの稼働状況を監視するコマンドは？", "options": ["top", "htop", "uptime", "vmstat"], "answer": "top"},
{"question": "Linuxでプロセスを強制終了するコマンドは？", "options": ["kill -9 PID", "kill PID", "pkill", "killall"], "answer": "kill -9 PID"},
{"question": "ログイン履歴を確認するコマンドは？", "options": ["last", "who", "w", "users"], "answer": "last"},
{"question": "Linuxの現在のカーネルバージョンを確認するコマンドは？", "options": ["uname -r", "uname -a", "cat /proc/version", "dmesg"], "answer": "uname -r"},
{"question": "カーネル情報を全て表示するコマンドは？", "options": ["uname -a", "uname -r", "cat /proc/version", "dmesg"], "answer": "uname -a"},
{"question": "ネットワーク設定を確認するコマンドは？", "options": ["ifconfig", "ip addr", "nmcli", "netstat"], "answer": "ifconfig"},
{"question": "ネットワーク設定を永続化して変更するコマンドは？", "options": ["nmcli", "ifconfig", "ip addr", "route"], "answer": "nmcli"},
{"question": "システム全体のメモリ使用状況を確認するコマンドは？", "options": ["free -h", "top", "htop", "vmstat"], "answer": "free -h"},
{"question": "Linuxでハードディスクをパーティション分割するコマンドは？", "options": ["fdisk", "parted", "cfdisk", "lsblk"], "answer": "fdisk"},
{"question": "ファイルの内容を標準出力に表示するコマンドは？", "options": ["cat", "less", "more", "tail"], "answer": "cat"},
{"question": "Linuxで現在の作業ディレクトリをツリー表示するコマンドは？", "options": ["tree", "ls -R", "find .", "du -a"], "answer": "tree"},
{"question": "特定のプロセスを名前で探すコマンドは？", "options": ["pgrep", "ps aux | grep", "pidof", "jobs"], "answer": "pgrep"},
{"question": "特定のプロセスを名前で強制終了するコマンドは？", "options": ["pkill", "kill", "killall", "xkill"], "answer": "pkill"}
]